services:
  duplicati: 
    container_name: git_duplicati
    image: lscr.io/linuxserver/duplicati:latest
    privileged: true  # Run the container in privileged mode
    ports:
      - 5020:8200 # Port for Web-login
    privileged: true # root rights
    restart: on-failure:3
    volumes:
      - /var/lib/docker/volumes/sharedDockerFolder/_data/duplicat/config/:/config
      - /var/lib/docker/volumes/sharedDockerFolder/_data/duplicat/backups/:/backups
      - /var/lib/docker/volumes/sharedDockerFolder/_data/duplicat/source/:/source
      - /var/lib/docker/volumes/sharedDockerFolder/_data/:/sharedDockerFolder
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS= #optional
