version: "3"

name: esp-home
services:
  esphome:
    container_name: esp-home
    image: esphome/esphome:stable
    ports:
      - "6053:6053/tcp" # Port for ESP-connection
      - "8010:6052/tcp" # Port for Web-login
      - "8266:8266/tcp" # Port for ESP-connection
    privileged: true
    restart: on-failure:3
    volumes:
      - "/sharedDockerFolder/esp-home/config:/config"
    env_file:
      - ../stack.env
# Environment variables on Portainer to be filled:
# USERNAME=<Username>
# PASSWORD=<Passwort>
