version: '3' 
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable" 
    ports:
     - "8030:8123/tcp" 
    volumes:
     - "/docker/homeassistent/data:/config"
     - "/docker/homeassistent/media:/media"
     - /run/audio:/run/audio:ro
     - /run/dbus:/run/dbus:ro
    restart: unless-stopped 
    environment:
      TZ: Europe/Berlin
    privileged: true
