version: "3"

name: homeassistant
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    ports:
      - "8000:8123/tcp" # Port for Web-login
    privileged: true
    restart: on-failure:3
    volumes:
      - "/sharedDockerFolder/homeassistant/data:/config"
      - "/sharedDockerFolder/homeassistant/media:/media"
      - /run/audio:/run/audio:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: Europe/Berlin