version: "3"

name: homeassistant
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    ports:
      - "8000:8123/tcp" # Port for Web-login
    privileged: true
    restart: on-failure:3
    volumes:
      - "/var/lib/docker/volumes/sharedDockerFolder/_data/homeassistant/data:/config"
      - "/var/lib/docker/volumes/sharedDockerFolder/_data/homeassistant/media:/media"
    environment:
      TZ: Europe/Berlin