services:
    it-tools:  # The service name
        container_name: git_it-tools  # The name of the container
        restart: on-failure:3  # Restart the container up to 3 times if it fails
        ports:
            - 7010:80  # Map port 7010 on the host to port 80 in the container
        environment:  # Environment variables for the container
            - UID=1000  # User ID set to 1000
            - GID=1000  # Group ID set to 1000
        image: 'corentinth/it-tools:latest'  # Use the latest version of the corentinth/it-tools image
