version: "3.9"

name: mosquitto
services:
  mosquitto:
    container_name: "mosquitto"
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883/tcp"
    restart: on-failure:3
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/sharedDockerFolder/mosquitto/data:/mosquitto/config"
      - "/sharedDockerFolder/mosquitto/data:/mosquitto/data"
      - "/sharedDockerFolder/mosquitto/data:/mosquitto/log"
    environment:
      - "TZ=Europe/Berlin"
    hostname: "ubmqtt"