version: "3"

# Mehr Infos auf https://github.com/pi-hole/docker-pi-hole/ und https://docs.pi-hole.net/
name: pihole
services:
  pihole:
    container_name: pihole # Der Name des Containers wie er in Portainer unter "Containers" angezeigt wird
    image: pihole/pihole:latest # Download des offiziellen Pihole-Images
    ports: # Für DHCP wird empfohlen, die folgenden Ports zu entfernen und stattdessen hinzuzufügen: network_mode: "host"
      - "53:53/tcp" # DNS Port
      - "53:53/udp"
      # - "67:67/udp" # Wird nur benötigt, wenn ihr Pi-hole als DHCP-Server nutzen wollt
      - "9010:80/tcp" # Port for Web-login
    restart: always # Startet immer neu
    volumes: # "Volumes" speichert Daten zwischen Container-Upgrades
      - "/sharedDockerFolder/pihole/config:/etc/pihole"
      - "/sharedDockerFolder/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    environment:
      TZ: "Europe/Berlin" # Die Zeitzone wird auf Deutschland gestellt
      PIHOLE_DNS_: "8.8.8.8;1.1.1.1" # Stellt in Pihole "Quad9 (filtered, DNSSEC)" als Upstream-DNS-Server ein statt Google
      REV_SERVER_TARGET: "192.168.178.1" # If conditional forwarding is enabled, set the IP of the local network router
    hostname: Home-Server # Diese Bezeichnung steht später oben rechts in der Weboberfläche von Pihole als Hostname
    dns:
      - 127.0.0.1
      - 8.8.8.8
    # cap_add: # Wird nur benötigt, wenn ihr Pi-hole als DHCP-Server nutzen wollt
    # - NET_ADMIN # Wird nur benötigt, wenn ihr Pi-hole als DHCP-Server nutzen wollt
    env_file:
      - ../stack.env
    # Environment variables on Portainer to be filled:
    # WEBPASSWORD: '<Passwort>' # Das Passwort, mit dem ihr euch an der Pihole-Weboberfläche anmeldet
    
