services:
  watchtower:
    container_name: git_watchtower  # The name of the container
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/sharedDockerFolder/_data/watchtower/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCHEDULE: 0 0 3 * * *
      TZ: Europe/Berlin
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
      