version: "3"

name: watchtower
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /sharedDockerFolder/watchtower/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCHEDULE: 0 0 3 * * *
      TZ: Europe/Berlin
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
      